import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import styled from 'styled-components'
import BlockWorld from '@/components/BlockWorld'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Next</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={`${styles.main} ${inter.className}`}>
				<BlockWorld />
			</main>
		</>
	)
}


const CenterWrap = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
`